### ISSUE TITLE
README prometheus issue?

### ISSUE THREAD

**Issue by ArKam** [mrlhansen/idrac_exporter#102]
Hi, I'm having a hard time understanding how your example about the single idrac_exporter for multiple BMC targets would work.

In your example, you put the distant BMC IPs as the targets list, however, this directive is used by prometheus to connect to the exporter itself, not to pass data to the exporter.

According to my knowledge (which may well be not complete) the example should rather look like:

```yaml
scrape_configs:
  - job_name: idrac
    static_configs:
      - targets: <exporter_ip:exporter_port>
    params:
      target: ['123.45.6.78', '123.45.6.79']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: exporter:9348
```

Or am I missing something?
