### ISSUE TITLE
Add a Dynamic Collector for the Exporter

### ISSUE THREAD

**Issue by mmelicias** [mrlhansen/idrac_exporter#128]
The Idea was to read the idrac yaml configuration file in a dynamic way:
Prometheus Configuration:
- job_name: 'idrac'
    scrape_interval: 240s
    scrape_timeout: 220s

    static_configs:
      - targets: ['x']
      - targets: ['y']
      - targets: ['w']
 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instancescrape_configs:

have something like this:   
- job_name: 'idrac'
    scrape_interval: 240s
    scrape_timeout: 220s

    http_sd_configs:
      - url: http://localhost:9348/request

      - target_label: __address__
        replacement: localhost:9348

address: localhost
port: 9348
timeout: 40

hosts:
 x:
    username: user
    password: pass
 y:
    username: user
    password: pass
 w:
    username: user
    password: pass
metrics:
  system: true
  sensors: true
  power: true
  events: true
  storage: true
  memory: true
  network: true
  oem: true
events:
  severity: warning
  maxage: 180d

With that improvement we not need to change 2 files each time a server is added .

**Comment by mrlhansen** [comment]
Hi @mmelicias 

This should not be very difficult, I am putting it on the TODO list.

**Comment by mrlhansen** [comment]
Okay, this was pretty simple. I pushed some changes that implements this. I tested that it works with the following Prometheus configuration.

```yaml
- job_name: idrac
  http_sd_configs:
    - url: http://localhost:9348/discover
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__meta_url]
      target_label: __address__
      regex: (https?.{3})([^\/]+)(.+)
      replacement: $2
```

I have quite a lot of things to implement at the moment, but this will be included in the next release.
