### ISSUE TITLE
Problem with yaml of idrac.yml

### ISSUE THREAD

**Issue by lesomora** [mrlhansen/idrac_exporter#25]
Hi thanks for this exporter,

I'm try using with docker image and my config is this: 

```
address: 0.0.0.0 # Listen address
port: 9348         # Listen port
timeout: 10        # HTTP timeout (in seconds) for Redfish API calls
retries: 1         # Number of retries before a target is marked as unreachable
hosts:
  default:
    username: user
    password: pass
metrics:
  system: true
  sensors: true
  power: true
  sel: false       # iDRAC only
  storage: false
  memory: false
``` 
but, when I try start the container. The application return:

line 10: cannot unmarshal !!map into []string

this error is happening on metrics lines.
