### ISSUE TITLE
Use dns-names of iDRAC instead IPs

### ISSUE THREAD

**Issue by mocart2** [mrlhansen/idrac_exporter#36]
Hi! When i use dns-names of iDRAC instead IPs exporter is filed on start, how i can fix it?

```
cat idrac.yml
address: 0.0.0.0 # Listen address
port: 9348         # Listen port
timeout: 180        # HTTP timeout (in seconds) for Redfish API calls
retries: 0        # Number of retries before a target is marked as unreachable
hosts:
  10.10.10.1:
    username: prometheus
    password: 123qweasd
  10.10.10.2:
    username: prometheus
    password: 123qweasd
metrics:
  system: true
  sensors: true
  power: true
  sel: true       # iDRAC only
  storage: true
  memory: true
```

and prometheus job:
```
      - job_name: idrac
        scrape_interval: 300s
        scrape_timeout: 180s
        static_configs:
          - targets: ["10.10.10.1", "10.10.10.2"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: "localhost:9348"
```
I need it, **idrac1.example.local** or **idrac2.example.local** , because in grafana variables, i want to use dns names of servers, use IPs is not convenient

**Comment by mrlhansen** [comment]
There should be no issues in using DNS names instead, as long as you do it in both places.

```yaml
address: 0.0.0.0 # Listen address
port: 9348         # Listen port
timeout: 180        # HTTP timeout (in seconds) for Redfish API calls
retries: 0        # Number of retries before a target is marked as unreachable
hosts:
  idrac1.example.local:
    username: prometheus
    password: 123qweasd
  idrac2.example.local:
    username: prometheus
    password: 123qweasd
metrics:
  system: true
  sensors: true
  power: true
  sel: true       # iDRAC only
  storage: true
  memory: true
```

and

```yaml
      - job_name: idrac
        scrape_interval: 300s
        scrape_timeout: 180s
        static_configs:
          - targets: ["idrac1.example.local", "idrac2.example.local"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: "localhost:9348"
```

**Comment by mocart2** [comment]
I configure my config with labels and use. **${host}** variable in Grafana, thanks!:
```
      - job_name: idrac
        scrape_interval: 300s
        scrape_timeout: 180s
        static_configs:
          - targets: ["10.10.10.1"]
            labels:
              host: idrac1.example.local
          - targets: ["10.10.10.2"]
            labels:
              host: idrac2.example.local
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: "{{ inventory_hostname }}:9348"
```
