### ISSUE TITLE
idrac_exporter works intermittently

### ISSUE THREAD

**Issue by niek1992** [mrlhansen/idrac_exporter#79]
Hi,

Tried to get `dellhw_exporter` working for quite a while, but then i found out it is intended for baremetal installs (which i do not do). But then i found your project and i was like "huh, this is what i should've been using all that time".

I however have some issues i can't seem to tackle with `idrac_exporter`. Below are the details and my troubleshooting steps i've taken:

- R630
- IDRAC8 (enterprise license)
- Lifecycle Controller Firmware: 2.85.85.85
- BIOS: 2.18.1
- mrlhansen/idrac_exporter:latest docker image
- idrac_exporter configured in iDRAC, with varying permissions (from Operator to Administrator)

`idrac_exporter` version:

```
2024-05-29T07:39:01.366 INFO  Build information: version=1.3.0 revision=ead63e5c64a0fdb76b84c39f2065900f784d4d0a
2024-05-29T07:39:01.366 INFO  Server listening on 0.0.0.0:9348
```

`/etc/prometheus/idrac.yml`:
```
address: 0.0.0.0 
port: 9348         
timeout: 60        
hosts:
  x.x.224.99:
    username: idrac_exporter
    password: "<snip>"
metrics:
  system: true
  sensors: true
  power: true
  sel: false
  storage: false
  memory: false
  network: false
```

Prometheus scrape config:

``` 
  - job_name: 'iDRAC R630'
    scrape_interval: 60s
    static_configs:
      - targets: ['x.x..224.99']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.x.x:9348
```

Output of `time` running from host where the exporter lives:
```
time curl localhost:9348/metrics?target=x.x.224.99
real    0m2.971s
user    0m0.004s
sys     0m0.007s
```

Output of `time` of my scraper, running on another machine in another VLAN:

```
time curl 192.168.x.x:9348/metrics?target=x.x.224.99
real    0m2.891s
user    0m0.010s
sys     0m0.000s
```

Initially i saw values of ~10s to do a scrape. I therefore decided to configure a scrape interval of 30s. I am aware of [your comment](https://github.com/mrlhansen/idrac_exporter?tab=readme-ov-file#:~:text=Because%20the%20metrics,scrape%20timeout%20value.) about carefully deciding which metrics i'd want to collect. I then decided to not do Storage, which let the scrape drop to ~3s. 

I also imported the dashboards made by [@7840vz](https://www.github.com/7840vz), but saw gaps in the graphs. Thinking it has something to do with the dashboard hard-coded for 1m refresh (and thus scrape) so i upped the scrape interval to 60s to match the dashboard. Didn't really help:

![image](https://github.com/mrlhansen/idrac_exporter/assets/31476400/294edbd7-bff8-4bb0-aa03-629274e5f808)

During troubleshooting i noticed that whenever i keep a session active on the webGUI of iDRAC itself, the graphs look _better_, but still not perfect:

![image](https://github.com/mrlhansen/idrac_exporter/assets/31476400/17b06ce7-06d8-4bb9-806e-adda91617f65)

Leading to think it's some sort of powersaving feature on iDRAC itself, but there is no "powersaving" feature for iDRAC itself, only the host OS running on the machine.

I'm almost out of ideas, and am thinking of diving into the rabbithole called `snmp_exporter` with MIB's from Dell to use SNMP to monitor my server. But ideally i would use this exporter, as i can simply point it to an iDRAC, configure credentials and it _just works_ (although intermittently at my side).

If you need any more information i can provide that for you, just ask 🙃.
