### ISSUE TITLE
Exporter stopped working after upgrading to iDrac 9 version 7 (Dell)

### ISSUE THREAD

**Issue by mymaor89** [mrlhansen/idrac_exporter#90]
After upgrading to iDrac 9 version 7 (February 2024 release) exporter stopped working

- Server model: Dell PowerEdge R740xd

 exporter fail with message: 
> ERROR Error instantiating metrics collector for host server-idrac.acme.local: 400 400 Bad Request
* container image: mrlhansen/idrac_exporter:1.4.1 (1.3.0 also didn't work)
* Redfish is enabled
* Using Administrator account to authenticate with all privileges
Config file:
```
address: 0.0.0.0
port: 9348
timeout: 60
retries: 0
hosts:
  default:
    username: admin
    password: superS3cr3tP@ssword

metrics:
  system: true   # CONFIG_METRICS_SYSTEM=true
  sensors: true  # CONFIG_METRICS_SENSORS=true
  power: true    # CONFIG_METRICS_POWER=true
  events: true   # CONFIG_METRICS_EVENTS=true
  storage: true  # CONFIG_METRICS_STORAGE=true
  memory: true   # CONFIG_METRICS_MEMORY=true
  network: true  # CONFIG_METRICS_NETWORK=true

events:
  severity: warning  # CONFIG_EVENTS_SEVERITY=warning
  maxage: 7d         # CONFIG_EVENTS_MAXAGE=7d
```
