### ISSUE TITLE
-config not working

### ISSUE THREAD

**Issue by helgesimo** [mrlhansen/idrac_exporter#94]
if default idrac.yml do not exsist, then the container keeps restarting before "exec bin/idrac_exporter -config=/my/path/configfile.yaml" can apply.

**Comment by mrlhansen** [comment]
Hi @helgesimo 

I am not able to reproduce the problem. Are you running the latest version? If I run e.g. the following, it works as expected:

```
$ docker run --rm -v $(pwd)/default-config.yml:/my/custom/config.yml idrac_exporter -verbose -config /my/custom/config.yml
2024-08-23T05:09:07.462 INFO  Build information: version=1.4.0 revision=7dac8e94908d7d8258c02bac492e680676af437e
2024-08-23T05:09:07.463 INFO  Server listening on 0.0.0.0:8888
```

**Comment by helgesimo** [comment]
Hello! :)

Here's my docker compose:

````yaml
#idrac-exporter
  idrac-exporter:
    image: mrlhansen/idrac_exporter:1.4.1 
    container_name: idrac-exporter
    restart: unless-stopped
    networks: 
      - metrics_net    
    ports:
      - "9348:9348"
    command:
      - "exec bin/idrac_exporter -config=/etc/prometheus/idrac.yaml"
    volumes:
      - $DOCKERDIR/idrac-exporter/config:/etc/prometheus/

````
So not a big change, i just want my .yaml instead of .yml to keep my configs tidy.

I need to keep the  idrac.yml and then run the custom command. If not, it seems it just reboots. 
Maybe my docker-compose.yaml is to blame.
